<#
.SYNOPSIS
    Merges multiple single-tenant Azure cost CSV reports into a single consolidated master report.

.DESCRIPTION
    Scans the specified input directory for cost report CSVs (flat or pivoted) generated by
    azure-cost-report.ps1 across different tenants (e.g. "AlternativeSoft" and "AlternativeSoft.cloud"),
    combines all subscription cost records, and produces a unified master report in both long (flat)
    and wide (pivoted) formats.

.PARAMETER InputDir
    Directory containing individual tenant cost CSV files. Defaults to "Output" (falls back to ".").

.PARAMETER Files
    Explicit list of CSV file paths to merge. If omitted, all matching cost CSV files in InputDir are used.

.PARAMETER OutputDir
    Directory where merged master CSV files will be saved. Defaults to "Output".

.NOTES
    READ-ONLY GUARANTEE:
    This script performs purely local file processing and calculations. No network or Azure calls are made.

.EXAMPLE
    pwsh AzureCost/Merge-CostReports.ps1
    pwsh AzureCost/Merge-CostReports.ps1 -InputDir "Output" -OutputDir "Output"
    pwsh AzureCost/Merge-CostReports.ps1 -Files @("Output/cost_AlternativeSoft_flat_20260805_1746.csv", "Output/cost_AlternativeSoft_cloud_flat_20260805_1746.csv")
#>

param(
    [string]$InputDir = "Output",

    [string[]]$Files,

    [string]$OutputDir = "Output"
)

# ------------------------------------------------------------------
# 1. Resolve Input Files
# ------------------------------------------------------------------
$flatFiles = @()

if ($Files -and $Files.Count -gt 0) {
    foreach ($f in $Files) {
        if (Test-Path $f) {
            $flatFiles += (Resolve-Path $f).Path
        } else {
            Write-Warning "Specified file not found: $f"
        }
    }
} else {
    $searchDir = $InputDir
    if (-not (Test-Path $searchDir)) {
        if (Test-Path "Output") {
            $searchDir = "Output"
        } elseif (Test-Path "../Output") {
            $searchDir = "../Output"
        } else {
            $searchDir = "."
        }
    }

    Write-Host "Searching for cost reports in: $searchDir" -ForegroundColor Cyan
    $foundFiles = Get-ChildItem -Path $searchDir -Filter "cost_*_flat_*.csv" -File | Sort-Object LastWriteTime -Descending

    # If no flat files found, check for generic cost_*.csv excluding MASTER files
    if (-not $foundFiles) {
        $foundFiles = Get-ChildItem -Path $searchDir -Filter "cost_*.csv" -File | Where-Object { $_.Name -notlike "*MASTER*" -and $_.Name -like "*flat*" }
    }

    # Group by tenant name prefix to pick the latest file per tenant if multiple runs exist
    $tenantGroups = $foundFiles | Group-Object {
        if ($_.BaseName -match '^cost_(.+)_flat_\d{8}_\d{4}$') {
            $Matches[1]
        } else {
            $_.BaseName
        }
    }

    foreach ($group in $tenantGroups) {
        $latest = $group.Group | Sort-Object LastWriteTime -Descending | Select-Object -First 1
        $flatFiles += $latest.FullName
    }
}

if (-not $flatFiles -or $flatFiles.Count -eq 0) {
    Write-Error "No matching flat cost report CSV files found in '$InputDir' or current directory. Run azure-cost-report.ps1 first."
    return
}

Write-Host "`nFound $($flatFiles.Count) cost report file(s) to merge:" -ForegroundColor Green
foreach ($f in $flatFiles) {
    Write-Host "  - $(Split-Path $f -Leaf)" -ForegroundColor Gray
}

function Normalize-MonthKey($rawDate) {
    if ($null -eq $rawDate) { return $null }
    $rawStr = $rawDate.ToString().Trim()

    # Case 1: dd/MM/yyyy or d/M/yyyy (e.g. 01/09/2025 or 01/09/2025 00:00:00)
    if ($rawStr -match "^(\d{1,2})[/\-](\d{1,2})[/\-](\d{4})") {
        $firstNum  = [int]$Matches[1]
        $secondNum = [int]$Matches[2]
        $year      = $Matches[3]

        if ($firstNum -eq 1 -and $secondNum -ge 1 -and $secondNum -le 12) {
            $month = $secondNum.ToString().PadLeft(2, "0")
            return "$year-$month-01"
        } elseif ($secondNum -gt 12 -and $firstNum -ge 1 -and $firstNum -le 12) {
            $month = $firstNum.ToString().PadLeft(2, "0")
            return "$year-$month-01"
        } elseif ($firstNum -gt 12 -and $secondNum -ge 1 -and $secondNum -le 12) {
            $month = $secondNum.ToString().PadLeft(2, "0")
            return "$year-$month-01"
        } else {
            $month = $secondNum.ToString().PadLeft(2, "0")
            return "$year-$month-01"
        }
    }

    # Case 2: yyyy-MM-dd or yyyy/MM/dd or yyyy-MM
    if ($rawStr -match "^(\d{4})[/\-](\d{1,2})") {
        $year = $Matches[1]
        $month = [int]$Matches[2]
        $monthStr = $month.ToString().PadLeft(2, "0")
        return "$year-$monthStr-01"
    }

    # Case 3: 8-digit integer like 20251201 or "20251201"
    if ($rawStr -match "^(\d{4})(\d{2})(\d{2})$") {
        return "$($Matches[1])-$($Matches[2])-01"
    }

    # Case 4: 6-digit integer like 202512 or "202512"
    if ($rawStr -match "^(\d{4})(\d{2})$") {
        return "$($Matches[1])-$($Matches[2])-01"
    }

    # Case 5: General DateTime parsing fallback
    $parsedDate = [DateTime]::MinValue
    if ([DateTime]::TryParse($rawStr, [System.Globalization.CultureInfo]::InvariantCulture, [System.Globalization.DateTimeStyles]::None, [ref]$parsedDate)) {
        return (Get-Date -Year $parsedDate.Year -Month $parsedDate.Month -Day 1).ToString("yyyy-MM-01")
    }

    return $rawStr
}

# ------------------------------------------------------------------
# 2. Ingest and Normalize Flat Data
# ------------------------------------------------------------------
$allFlatRows = @()

foreach ($filePath in $flatFiles) {
    try {
        $rows = Import-Csv -Path $filePath -ErrorAction Stop
        foreach ($r in $rows) {
            $costVal = 0.0
            if ($r.Cost) {
                [double]::TryParse($r.Cost, [ref]$costVal) | Out-Null
            }
            $costVal = [math]::Round($costVal, 2)

            $mKey = if ($r.Month) { Normalize-MonthKey $r.Month } else { "" }

            $allFlatRows += [PSCustomObject]@{
                TenantName       = if ($r.TenantName) { $r.TenantName.Trim() } else { "Unknown" }
                SubscriptionName = if ($r.SubscriptionName) { $r.SubscriptionName.Trim() } else { "Unknown" }
                SubscriptionId   = if ($r.SubscriptionId) { $r.SubscriptionId.Trim() } else { "" }
                Month            = $mKey
                PricingModel     = if ($r.PricingModel) { $r.PricingModel.Trim() } else { "OnDemand" }
                Cost             = $costVal
                Currency         = if ($r.Currency) { $r.Currency.Trim() } else { "USD" }
            }
        }
    } catch {
        Write-Warning "Could not read CSV file $filePath : $($_.Exception.Message)"
    }
}

if ($allFlatRows.Count -eq 0) {
    Write-Error "No data records could be parsed from the selected CSV files."
    return
}

# ------------------------------------------------------------------
# 3. Scope & Summary
# ------------------------------------------------------------------
$allMonths = @($allFlatRows | Select-Object -ExpandProperty Month -Unique | Where-Object { [string]::IsNullOrWhiteSpace($_) -eq $false } | Sort-Object)

if ($allMonths.Count -eq 0) {
    Write-Error "No month values found in the input records."
    return
}

$monthRangeDisplay = if ($allMonths.Count -gt 1) {
    "$($allMonths[0]) to $($allMonths[-1])"
} else {
    "$($allMonths[0])"
}

$allSubs = $allFlatRows | Select-Object TenantName, SubscriptionName, SubscriptionId | Sort-Object TenantName, SubscriptionName -Unique

Write-Host "`nConsolidated Scope:" -ForegroundColor Cyan
Write-Host "  Tenants:       $(($allSubs | Select-Object -ExpandProperty TenantName -Unique).Count)"
Write-Host "  Subscriptions: $($allSubs.Count)"
Write-Host "  Months:        $($allMonths.Count) ($monthRangeDisplay)"

# ------------------------------------------------------------------
# 4. Summary Table Output
# ------------------------------------------------------------------
Write-Host "`n=== COST SUMMARY BY TENANT ===" -ForegroundColor Green
$tenantSummaries = @()
$groupedByTenant = $allFlatRows | Group-Object TenantName

foreach ($tg in $groupedByTenant) {
    $tRes = ($tg.Group | Where-Object { $_.PricingModel -eq "Reservation" } | Measure-Object -Property Cost -Sum).Sum
    $tOnD = ($tg.Group | Where-Object { $_.PricingModel -eq "OnDemand" } | Measure-Object -Property Cost -Sum).Sum
    $tSav = ($tg.Group | Where-Object { $_.PricingModel -eq "SavingsPlan" } | Measure-Object -Property Cost -Sum).Sum
    $tTot = ($tg.Group | Measure-Object -Property Cost -Sum).Sum
    $subCount = ($tg.Group | Select-Object -ExpandProperty SubscriptionId -Unique).Count

    $tenantSummaries += [PSCustomObject]@{
        TenantName        = $tg.Name
        Subscriptions     = $subCount
        Total_Reservation = [math]::Round((if ($tRes) { $tRes } else { 0.0 }), 2)
        Total_OnDemand    = [math]::Round((if ($tOnD) { $tOnD } else { 0.0 }), 2)
        Total_SavingsPlan = [math]::Round((if ($tSav) { $tSav } else { 0.0 }), 2)
        Grand_Total       = [math]::Round((if ($tTot) { $tTot } else { 0.0 }), 2)
    }
}
$tenantSummaries | Format-Table -AutoSize

# ------------------------------------------------------------------
# 5. Export Master Flat CSV
# ------------------------------------------------------------------
if (-not (Test-Path $OutputDir)) {
    New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
}

$timestamp = Get-Date -Format 'yyyyMMdd_HHmm'
$masterFlatPath = Join-Path $OutputDir "cost_MASTER_flat_$timestamp.csv"

$allFlatRows | Sort-Object Month, TenantName, SubscriptionName, PricingModel | Export-Csv -Path $masterFlatPath -NoTypeInformation
Write-Host "`nExported master cost CSV: $masterFlatPath" -ForegroundColor Cyan

Write-Host "`nMerge complete. Combined $($allSubs.Count) subscriptions across $(($tenantSummaries).Count) tenant(s)." -ForegroundColor Green
